openapi: 3.0.3
info:
  title: OptHub REST API
  description: |-
    OptHub Public REST API.
  termsOfService: https://example.com/todo/opthub-api-term-of-service
  contact:
    email: dev@opthub.ai
  license:
    name: MIT
    url: https://opensource.org/license/mit/
  version: 0.1.0

servers:
  - url: https://example.com/todo/opthub-api-endpoint

tags:
  - name: solution
    description: Operations about solution.
  - name: analyzer
    description: Access to past competitions.
  - name: competition
    description: Operations about competition.
  - name: match
    description: Operations about match.
  - name: participant
    description: Operations about participant.
  - name: alias
    description: Operations about alias.

paths:
  /competition/alias/{alias}:
    get:
      tags:
        - competition
        - alias
      summary: Retrieve the competition ID from the competition alias
      operationId: resolveCompetitionIdByAlias
      parameters:
        - name: alias
          in: path
          description: Competition alias
          required: true
          schema:
            $ref: '#/components/schemas/CompetitionAlias'
          example: "competition123"
      responses:
        '200':
          description: Competition ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompetitionId'
        '404':
          description: Competition not found
      security:
        - ApiKeyAuth: []

  /competition/{id}/alias:
    get:
      tags:
        - competition
        - alias
      summary: Retrieve the competition alias from the competition ID
      operationId: resolveCompetitionAliasById
      parameters:
        - name: id
          in: path
          description: Competition ID
          required: true
          schema:
            $ref: '#/components/schemas/CompetitionId'
          example: 42c999a1-a30c-47ef-b656-eb49f67488dc
      responses:
        '200':
          description: Competition alias
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompetitionAlias'
        '404':
          description: Competition not found
      security:
        - ApiKeyAuth: []

  /competition/match/alias/{alias}:
    get:
      tags:
        - match
        - alias
      summary: Retrieve the match ID from the match alias
      operationId: resolveMatchIdByAlias
      parameters:
        - name: alias
          in: path
          description: Match alias
          required: true
          schema:
            $ref: '#/components/schemas/MatchAlias'
          example: "match123"
      responses:
        '200':
          description: Match ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatchId'
        '404':
          description: Match not found
      security:
        - ApiKeyAuth: []

  /competition/match/{matchId}/alias:
    get:
      tags:
        - match
        - alias
      summary: Retrieve the match alias from the match ID
      operationId: resolveMatchAliasById
      parameters:
        - name: matchId
          in: path
          description: Match ID
          required: true
          schema:
            $ref: '#/components/schemas/MatchId'
          example: 5d7fc778-3e59-4128-a797-2e423c0aa461
      responses:
        '200':
          description: Match alias
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatchAlias'
        '404':
          description: Match not found
      security:
        - ApiKeyAuth: []

  /competition/match/{matchId}/solution:
    post:
      tags:
        - solution
      summary: Create solution
      operationId: createSolution
      parameters:
        - name: matchId
          in: path
          description: Match ID
          required: true
          schema:
            $ref: '#/components/schemas/MatchId'
          example: 5d7fc778-3e59-4128-a797-2e423c0aa461
        - name: variable
          in: query
          description: Solution space variable
          required: true
          schema:
            type: array
            items:
              type: number
              format: double
            example: [1.234, -5.678, 9.1011]
      responses:
        '200':
          description: Information of the created solution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateSolutionResponse'
        '404':
          description: Match not found
      security:
        - ApiKeyAuth: []

    get:
      tags:
        - solution
      summary: Retrive solution
      operationId: getSolution
      parameters:
        - name: matchId
          in: path
          description: Match ID
          required: true
          schema:
            $ref: '#/components/schemas/MatchId'
          example: 5d7fc778-3e59-4128-a797-2e423c0aa461
        - name: participantId
          in: query
          description: Participant ID
          required: true
          schema:
            $ref: '#/components/schemas/ParticipantId'
          example: 912f548d-2bbe-48ab-90ce-e96dae38377d
        - name: trialNo
          in: query
          description: Trial number
          required: true
          schema:
            type: integer
            format: int32
            example: 4
      responses:
        '200':
          description: Information of the solution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Solution'
        '404':
          description: The created solution specified in the query was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetSolutionError'
      security:
        - ApiKeyAuth: []

components:
  schemas:
    CreateSolutionResponse:
      description: Information of the created solution
      type: object
      properties:
        participantId:
          $ref: '#/components/schemas/ParticipantId'
        trialNo:
          type: integer
          format: int32
          description: Trial number
          example: 4
      required:
        - participantId
        - trialNo

    Solution:
      description: 解
      type: object
      properties:
        matchId:
          description: Match ID
          type: string
          format: uuid
          example: 5d7fc778-3e59-4128-a797-2e423c0aa461
        trialNo:
          description: Trial number
          type: integer
          format: int32
          example: 4
        variable:
          description: Solution space variable
          type: array
          items:
            type: number
            format: double
          example: [1.234, -5.678, 9.1011]
        createdAt:
          description: Creation date and time
          type: string
          format: date-time
          example: 2024-08-06T10:11:45.789Z
        userId:
          description: ID of the user who created it
          type: string
          format: uuid
          example: 1e892e70-47ba-4c8e-8563-6aea9019e334
      required:
        - matchId
        - trialNo
        - variable
        - createdAt

    GetSolutionError:
      description: Failed to retrieve the solution
      type: string
      enum:
        - InvalidMatchId
        - InvalidParticipantId
        - TrialNotFound

    Participant:
      description: Participant information
      type: object
      properties:
        participantType:
          $ref: '#/components/schemas/ParticipantType'
      required:
        - participantType

    ParticipantId:
      description: Participant ID
      type: string
      format: uuid
      example: 912f548d-2bbe-48ab-90ce-e96dae38377d

    ParticipantType:
      description: Participant type
      type: string
      enum:
        - User
        - Team
      example: User

    CompetitionId:
      description: Competition ID
      type: string
      format: uuid
      example: 42c999a1-a30c-47ef-b656-eb49f67488dc

    CompetitionAlias:
      description: Competition alias
      type: string
      example: "competition123"

    MatchId:
      description: Match ID
      type: string
      format: uuid
      example: 5d7fc778-3e59-4128-a797-2e423c0aa461

    MatchAlias:
      description: Match alias
      type: string
      example: "match123"

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
