openapi: 3.0.3
info:
  title: OptHub REST API
  description: |-
    OptHub Public REST API.
  termsOfService: https://example.com/todo/opthub-api-term-of-service
  contact:
    email: dev@opthub.ai
  license:
    name: MIT
    url: https://opensource.org/license/mit/
  version: 0.2.0

servers:
  - url: https://example.com/todo/opthub-api-endpoint

tags:
  - name: solution
    description: Operations about solution.
  - name: trial
    description: Operations about trial.

paths:
  /matches/{match_uuid}/solutions:
    post:
      tags:
        - solution
      summary: Create solution
      operationId: createSolution
      parameters:
        - name: match_uuid
          in: path
          description: Match UUID
          required: true
          schema:
            $ref: '#/components/schemas/MatchUuid'
          example: 5d7fc778-3e59-4128-a797-2e423c0aa461
      requestBody:
        content:
          application/json:
            schema:
              description: Solution space variable
              $ref: '#/components/schemas/Variable'
              example: [1.234, -5.678, 9.1011]
      responses:
        '200':
          description: Information of the created Solution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateSolutionResponse'
        '400':
          description: Invalid format. The solution variable's JSON object must contain either a scalar or a vector, but not both.
        '404':
          description: No such Match UUID
      security:
        - ApiKeyAuth: []

  /matches/{match_uuid}/trials/{trial_no}/solution:
    get:
      tags:
        - solution
      summary: Retrieve a solution submitted by the participant themselves.
      operationId: getSolution
      parameters:
        - name: match_uuid
          in: path
          description: Match UUID
          required: true
          schema:
            $ref: '#/components/schemas/MatchUuid'
          example: 5d7fc778-3e59-4128-a797-2e423c0aa461
        - name: trial_no
          in: path
          description: Trial number
          required: true
          schema:
            type: integer
            format: int32
            example: 4
          example: 4
      responses:
        '200':
          description: Information of the Solution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Solution'
        '404':
          description: The trial specified in the query was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatchTrialNotFound'
      security:
        - ApiKeyAuth: []

  /matches/{match_uuid}/trials/{trial_no}:
    get:
      tags:
        - trial
      summary: |-
        Retrieve status of a specific Trial related to the Solution submitted by the Participant themselves.
      operationId: getMatchTrial
      parameters:
        - name: match_uuid
          in: path
          description: Match UUID
          required: true
          schema:
            $ref: '#/components/schemas/MatchUuid'
          example: 5d7fc778-3e59-4128-a797-2e423c0aa461
        - name: trial_no
          in: path
          description: Trial number
          required: true
          schema:
            type: integer
            format: int32
            example: 4
          example: 4
      responses:
        '200':
          description: Status information of the Trial
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatchTrialStatus'
        '404':
          description: The trial specified in the query was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatchTrialNotFound'
      security:
        - ApiKeyAuth: []


components:
  schemas:
    CreateSolutionResponse:
      description: Information of the created Solution
      type: object
      properties:
        trial_no:
          type: integer
          format: int32
          description: Trial number
          example: 4
      required:
        - trial_no

    MatchTrialStatus:
      description: Match Trial status information
      type: object
      properties:
        type:
          description: Types of trial status.
          $ref: '#/components/schemas/MatchTrialStatusType'
        evaluation:
          description: Evaluation results
          $ref: '#/components/schemas/MatchTrialEvaluation'
        score:
          description: Results of Score calculation
          $ref: '#/components/schemas/MatchTrialScore'
      required:
        - type

    MatchTrialStatusType:
      description: Types of trial status.
      type: string
      enum:
        - Success
        - Scoring
        - Evaluating
        - ScorerFailed
        - EvaluatorFailed

    MatchTrialEvaluation:
      description: Evaluation results
      type: object
      properties:
        objective:
          description: The value of the objective function
          $ref: '#/components/schemas/Variable'
        constraint:
          description: The value of the constraint condition
          $ref: '#/components/schemas/Vector'
          nullable: true
        feasible:
          description: Whether it is a feasible solution
          type: boolean
        extra_info:
          description: Auxiliary information for evaluation
          type: object
        started_at:
          description: Evaluation start date and time
          type: string
          format: date-time
          example: 2024-08-29T10:12:58.123Z
        finished_at:
          description: Evaluation end date and time
          type: string
          format: date-time
          example: 2024-08-29T10:34:01.592Z
        error:
          description: Evaluation error information
          type: string
        status:
          description: Evaluation status
          $ref: '#/components/schemas/RunnerStatus'
      required:
        - status

    RunnerStatus:
      description: Status of the Trial
      type: string
      enum:
        - Success
        - Failed

    MatchTrialScore:
      description: Results of Score calculation
      type: object
      properties:
        value:
          description: The value of the Score
          type: number
          format: double
          example: 15.1617
        started_at:
          description: Score calculation start date and time
          type: string
          format: date-time
          example: 2024-08-29T10:56:02.933Z
        finished_at:
          description: Score calculation end date and time
          type: string
          format: date-time
          example: 2024-08-29T11:01:21.319Z
        error:
          description: Score calculation error information
          type: string
        status:
          description: Score calculation status
          $ref: '#/components/schemas/RunnerStatus'
      required:
        - status

    Solution:
      description: Solution information
      type: object
      properties:
        variable:
          description: Solution space variable
          $ref: '#/components/schemas/Variable'
        created_at:
          description: Creation date and time
          type: string
          format: date-time
          example: 2024-08-06T10:11:45.789Z
        created_by:
          description: UUID of the user who created it
          $ref: '#/components/schemas/UserUuid'
      required:
        - variable
        - created_at
        - created_by

    MatchTrialNotFound:
      description: The reason why the trial was not found.
      type: string
      enum:
        - InvalidMatchUuid
        - NoSuchTrialNo

    MatchUuid:
      description: Match UUID
      type: string
      format: uuid
      example: 5d7fc778-3e59-4128-a797-2e423c0aa461

    UserUuid:
      description: User UUID
      type: string
      format: uuid
      example: 1e892e70-47ba-4c8e-8563-6aea9019e334

    Variable:
      description: A double-precision floating-point scalar or vector.
      type: object
      properties:
        vector:
          description: Vector case
          $ref: '#/components/schemas/Vector'
        scalar:
          description: Scalar case
          $ref: '#/components/schemas/Scalar'
      example: "{vector: [1.234, -5.678, 9.1011]}"

    Scalar:
      description: A double-precision floating-point scalar value
      type: number
      format: double
      example: -12.1314

    Vector:
      description: A double-precision floating-point vector.
      type: array
      items:
        type: number
        format: double
      example: [1.234, -5.678, 9.1011]

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
