openapi: 3.0.3
info:
  title: OptHub REST API
  description: |-
    OptHubの公開REST APIです。
  termsOfService: https://example.com/todo/opthub-api-term-of-service
  contact:
    email: dev@opthub.ai
  license:
    name: MIT
    url: https://opensource.org/license/mit/
  version: 0.1.0

servers:
  - url: https://example.com/todo/opthub-api-endpoint

tags:
  - name: solution
    description: 解に関する操作
  - name: analyzer
    description: 過去コンペティションへのアクセス

paths:
  /solution:
    post:
      tags:
        - solution
      summary: 解の作成
      operationId: createSolution
      parameters:
        - name: matchId
          in: query
          description: 競技のID
          required: true
          schema:
            type: string
            format: uuid
          example: 5d7fc778-3e59-4128-a797-2e423c0aa461
        - name: variable
          in: query
          description: 解空間の変数
          required: true
          schema:
            type: array
            items:
              type: number
              format: double
            example: [1.234, -5.678, 9.1011]
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateSolutionResponse'
        default:
          description: successful operation
      security:
        - ApiKeyAuth: []

    get:
      tags:
        - solution
      summary: 解の取得
      operationId: getSolution
      parameters:
        - name: matchId
          in: query
          description: 競技のID
          required: true
          schema:
            type: string
            format: uuid
          example: 5d7fc778-3e59-4128-a797-2e423c0aa461
        - name: participantId
          in: query
          description: 参加者のID
          required: true
          schema:
            type: string
            format: uuid
          example: 912f548d-2bbe-48ab-90ce-e96dae38377d
        - name: trialNo
          in: query
          description: 試行番号
          required: true
          schema:
            type: integer
            format: int32
            example: 4
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Solution'
        default:
          description: successful operation
      security:
        - ApiKeyAuth: []

components:
  schemas:
    CreateSolutionResponse:
      description: 解の作成リクエストの結果
      type: object
      properties:
        matchId:
          type: string
          format: uuid
          description: 競技のID
          example: 5d7fc778-3e59-4128-a797-2e423c0aa461
        participantType:
          $ref: '#/components/schemas/ParticipantType'
        participantId:
          type: string
          format: uuid
          description: 参加者のID
          example: 912f548d-2bbe-48ab-90ce-e96dae38377d
        trialNo:
          type: integer
          format: int32
          description: 試行番号
          example: 4
      required:
        - matchId
        - participantType
        - participantId
        - trialNo

    Solution:
      description: 解
      type: object
      properties:
        matchId:
          description: 競技のID
          type: string
          format: uuid
          example: 5d7fc778-3e59-4128-a797-2e423c0aa461
        participantType:
          $ref: '#/components/schemas/ParticipantType'
        participantId:
          description: 参加者のID
          type: string
          format: uuid
          example: 912f548d-2bbe-48ab-90ce-e96dae38377d
        trialNo:
          description: 試行番号
          type: integer
          format: int32
          example: 4
        variable:
          description: 解空間の変数
          type: array
          items:
            type: number
            format: double
          example: [1.234, -5.678, 9.1011]
        createdAt:
          description: 作成日時
          type: string
          format: date-time
          example: 2024-08-06T10:11:45.789Z
        userId:
          description: 作成したユーザのID
          type: string
          format: uuid
          example: 1e892e70-47ba-4c8e-8563-6aea9019e334
      required:
        - matchId
        - participantType
        - participantId
        - trialNo
        - variable
        - createdAt

    ParticipantType:
      description: 参加者の種別
      type: string
      enum:
        - User
        - Team
      example: User

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
