openapi: 3.0.3
info:
  title: OptHub REST API
  description: |-
    OptHubの公開REST APIです。
  termsOfService: https://example.com/todo/opthub-api-term-of-service
  contact:
    email: dev@opthub.ai
  license:
    name: MIT
    url: https://opensource.org/license/mit/
  version: 0.1.0

servers:
  - url: https://example.com/todo/opthub-api-endpoint

tags:
  - name: solution
    description: 解に関する操作
  - name: analyzer
    description: 過去コンペティションへのアクセス
  - name: competition
    description: コンペティションに関する操作
  - name: match
    description: 競技に関する操作
  - name: alias
    description: エイリアスに関する操作

paths:
  /competition/alias/{alias}:
    get:
      tags:
        - competition
        - alias
      summary: コンペティションのエイリアスからコンペティションIDを取得
      operationId: resolveCompetitionIdByAlias
      parameters:
        - name: alias
          in: path
          description: コンペティションのエイリアス
          required: true
          schema:
            $ref: '#/components/schemas/CompetitionAlias'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompetitionId'
        default:
          description: successful operation
      security:
        - ApiKeyAuth: []

  /competition/{id}/alias:
    get:
      tags:
        - competition
        - alias
      summary: コンペティションIDからコンペティションのエイリアスを取得
      operationId: resolveCompetitionAliasById
      parameters:
        - name: id
          in: path
          description: コンペティションのID
          required: true
          schema:
            $ref: '#/components/schemas/CompetitionId'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompetitionAlias'
        default:
          description: successful operation
      security:
        - ApiKeyAuth: []

  /competition/match/alias/{alias}:
    get:
      tags:
        - match
        - alias
      summary: 競技のエイリアスから競技IDを取得
      operationId: resolveMatchIdByAlias
      parameters:
        - name: alias
          in: path
          description: 競技のエイリアス
          required: true
          schema:
            $ref: '#/components/schemas/MatchAlias'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatchId'
        default:
          description: successful operation
      security:
        - ApiKeyAuth: []

  /competition/match/{matchId}/alias:
    get:
      tags:
        - match
        - alias
      summary: 競技IDから競技のエイリアスを取得
      operationId: resolveMatchAliasById
      parameters:
        - name: matchId
          in: path
          description: 競技のID
          required: true
          schema:
            $ref: '#/components/schemas/MatchId'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatchAlias'
        default:
          description: successful operation
      security:
        - ApiKeyAuth: []

  /competition/match/{matchId}/solution:
    post:
      tags:
        - solution
      summary: 解の作成
      operationId: createSolution
      parameters:
        - name: matchId
          in: path
          description: 競技のID
          required: true
          schema:
            type: string
            format: uuid
          example: 5d7fc778-3e59-4128-a797-2e423c0aa461
        - name: variable
          in: query
          description: 解空間の変数
          required: true
          schema:
            type: array
            items:
              type: number
              format: double
            example: [1.234, -5.678, 9.1011]
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateSolutionResponse'
        default:
          description: successful operation
      security:
        - ApiKeyAuth: []

    get:
      tags:
        - solution
      summary: 解の取得
      operationId: getSolution
      parameters:
        - name: matchId
          in: path
          description: 競技のID
          required: true
          schema:
            type: string
            format: uuid
          example: 5d7fc778-3e59-4128-a797-2e423c0aa461
        - name: participantId
          in: query
          description: 参加者のID
          required: true
          schema:
            $ref: '#/components/schemas/ParticipantId'
        - name: trialNo
          in: query
          description: 試行番号
          required: true
          schema:
            type: integer
            format: int32
            example: 4
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Solution'
        default:
          description: successful operation
      security:
        - ApiKeyAuth: []

components:
  schemas:
    CreateSolutionResponse:
      description: 解の作成リクエストの結果
      type: object
      properties:
        participant:
          $ref: '#/components/schemas/Participant'
        trialNo:
          type: integer
          format: int32
          description: 試行番号
          example: 4
      required:
        - participantType
        - participantId
        - trialNo

    Solution:
      description: 解
      type: object
      properties:
        matchId:
          description: 競技のID
          type: string
          format: uuid
          example: 5d7fc778-3e59-4128-a797-2e423c0aa461
        participant:
          $ref: '#/components/schemas/Participant'
        trialNo:
          description: 試行番号
          type: integer
          format: int32
          example: 4
        variable:
          description: 解空間の変数
          type: array
          items:
            type: number
            format: double
          example: [1.234, -5.678, 9.1011]
        createdAt:
          description: 作成日時
          type: string
          format: date-time
          example: 2024-08-06T10:11:45.789Z
        userId:
          description: 作成したユーザのID
          type: string
          format: uuid
          example: 1e892e70-47ba-4c8e-8563-6aea9019e334
      required:
        - matchId
        - participantType
        - participantId
        - trialNo
        - variable
        - createdAt

    Participant:
      description: 参加者の情報
      type: object
      properties:
        participantId:
          $ref: '#/components/schemas/ParticipantId'
        participantType:
          $ref: '#/components/schemas/ParticipantType'
      required:
        - participantId
        - participantType

    ParticipantId:
      description: 参加者のID
      type: string
      format: uuid
      example: 912f548d-2bbe-48ab-90ce-e96dae38377d

    ParticipantType:
      description: 参加者の種別
      type: string
      enum:
        - User
        - Team
      example: User

    CompetitionId:
      description: コンペティションのID
      type: string
      format: uuid
      example: 42c999a1-a30c-47ef-b656-eb49f67488dc

    CompetitionAlias:
      description: コンペティションのエイリアス
      type: string
      example: "competition123"

    MatchId:
      description: 競技のID
      type: string
      format: uuid
      example: 5d7fc778-3e59-4128-a797-2e423c0aa461

    MatchAlias:
      description: 競技のエイリアス
      type: string
      example: "match123"

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
