name: Release

on:
  push:
    branches:
    - main

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true # Checkout submodules
        fetch-depth: 0 # Fetch all history for accurate versioning
    - uses: ./.github/workflows/actions/poetry_publish
      with:
        directory: opthub-api-client-python
        pypi: true
        pypi_token: ${{ secrets.PYPI_API_TOKEN }}

